/**
 * Part.js — the unit every anatomical structure is delivered as.
 *
 * A "part" is a THREE.LOD whose tiers are generated by one function, plus the
 * metadata the rest of the app needs (name, Latin term, region, system) carried
 * on `userData`. Keeping name/system on the object rather than in a side table
 * means picking, labelling, isolation and the layer panel all read from one
 * place, and a part can be moved between hierarchies without losing identity.
 */
import { Mesh, Sphere, Vector3 } from 'three';
import { buildLOD } from './quality.js';

let partSerial = 0;

/**
 * @param {object} def
 * @param {string} def.id        unique key, e.g. 'femur.right'
 * @param {string} def.name      English name, e.g. 'Femur'
 * @param {string} [def.latin]   Latin term, e.g. 'Os femoris'
 * @param {string} def.system    'skeletal' | 'muscular' | 'visceral' | 'nervous' | 'integumentary'
 * @param {string} def.region    'axial' | 'appendicular' | 'thoracic' | ...
 * @param {(q:number)=>import('three').BufferGeometry} def.build
 * @param {import('three').Material|((g:object)=>import('three').Material)} def.material
 * @param {number[]} [def.distances] LOD switch distances (metres)
 * @param {number} [def.q=1]     quality scalar multiplier for this part
 * @param {boolean} [def.castShadow=true]
 * @param {boolean} [def.receiveShadow=true]
 * @param {number} [def.renderOrder=0]
 * @param {string} [def.note]    short anatomical annotation shown in the UI
 */
export function makePart(def) {
  const {
    id,
    name,
    latin = '',
    system,
    region = '',
    build,
    material,
    distances = [0, 1.6, 3.2, 6.0],
    q = 1,
    castShadow = true,
    receiveShadow = true,
    renderOrder = 0,
    note = '',
  } = def;

  const makeObject = (geometry) => {
    const mat = typeof material === 'function' ? material(geometry) : material;
    const mesh = new Mesh(geometry, mat);
    mesh.castShadow = castShadow;
    mesh.receiveShadow = receiveShadow;
    mesh.renderOrder = renderOrder;
    mesh.name = id;
    return mesh;
  };

  const lod = buildLOD((qq) => build(qq * q), makeObject, { distances, baseQ: 1 });
  lod.name = id;
  lod.userData.part = {
    key: `part:${++partSerial}`,
    id,
    name,
    latin,
    system,
    region,
    note,
  };
  return lod;
}

/**
 * Cheaper path for structures that do not justify several tiers: a single mesh
 * still gets a bounding sphere and full metadata, and costs one draw call.
 */
export function makeStaticPart(def) {
  const {
    id,
    name,
    latin = '',
    system,
    region = '',
    build,
    material,
    q = 1,
    castShadow = true,
    receiveShadow = true,
    note = '',
  } = def;
  const geometry = build(q);
  const mat = typeof material === 'function' ? material(geometry) : material;
  const mesh = new Mesh(geometry, mat);
  mesh.castShadow = castShadow;
  mesh.receiveShadow = receiveShadow;
  mesh.name = id;
  mesh.userData.part = { key: `part:${++partSerial}`, id, name, latin, system, region, note };
  mesh.userData.triangles = geometry.index ? geometry.index.count / 3 : geometry.attributes.position.count / 3;
  return mesh;
}

/** World-space centre of a part — used to anchor labels and to focus the camera. */
export function partCentre(part, target = new Vector3()) {
  part.updateWorldMatrix(true, false);
  const sphere = partBoundingSphere(part);
  return target.copy(sphere.center);
}

/** Bounding sphere of the part in world space (largest visible tier). */
export function partBoundingSphere(part) {
  let best = null;
  part.updateWorldMatrix(true, false);
  part.traverse((o) => {
    if (!o.isMesh || !o.geometry) return;
    if (o.parent?.isLOD && !o.visible) return; // skip hidden LOD tiers
    if (!o.geometry.boundingSphere) o.geometry.computeBoundingSphere();
    const s = o.geometry.boundingSphere.clone().applyMatrix4(o.matrixWorld);
    if (!best || s.radius > best.radius) best = s;
  });
  return best ?? new Sphere(new Vector3(), 0.05);
}
